[project]
name = "spot-dl"
version = "0.1.0"
description = "Spotify Track/Playlist downloader."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyinstaller>=6.18.0",
    "requests>=2.32.5",
    "spotifyscraper>=2.1.5",
    "ytmusicapi>=1.11.4",
]
